### ISSUE TITLE
No service

### ISSUE THREAD

**Issue by psychomad** [kennyledet/Google-EmailScraper#2]
Hi
When i try to use the tool i got this:
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    s.go(args.query, args.pages)
  File "main.py", line 35, in go
    results = search.get_results()
  File "/root/Google-EmailScraper/xgoogle/search.py", line 150, in get_results
    page = self._get_results_page()
  File "/root/Google-EmailScraper/xgoogle/search.py", line 207, in _get_results_page
    raise SearchError, "Failed getting %s: %s" % (e.url, e.error)
xgoogle.search.SearchError: Failed getting http://www.google.com/search?hl=en&q=email+it&btnG=Google+Search: HTTP Error 503: Service Unavailable

If i try directly on google work fine...
Google reject query?

**Comment by FelixVicis** [comment]
Hello @psychomad,
A script that this scrapper had as a dependency stopped working quite a while ago. I have an outstanding PR to update this scrapper, but in the meantime you can use it directly from my fork at https://github.com/FelixVicis/Google-EmailScraper

**Comment by psychomad** [comment]
Hi
Thanks a lot!
