### ISSUE TITLE
urllib2.HTTPError: HTTP Error 999: Request denied and 403: Forbidden

### ISSUE THREAD

**Issue by kn9** [kennyledet/Google-EmailScraper#3]
Hello @FelixVicis, I get keep getting the error below when I try your forked Google-EmailScraper.
how can I resolve this, please

root@Inside:/home/amd/mail# sudo python main.py -query "Manage IT Services" -pages 10 -o ema.csv
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    s.go(args.query, args.pages)
  File "main.py", line 35, in go
    self.scrape(url)
  File "main.py", line 43, in scrape
    raise e
urllib2.HTTPError: HTTP Error 999: Request denied
root@Inside:/home/amd/mail# sudo python main.py -query "Manage IT Services" -pages 10 -o emaia.csv
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    s.go(args.query, args.pages)
  File "main.py", line 35, in go
    self.scrape(url)
  File "main.py", line 43, in scrape
    raise e
urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by FelixVicis** [comment]
Good morning @kn9,

I'm going to move your bug report over to my repo so that I can properly track the problem.

**Comment by dray89** [comment]
Similar issue when trying to run command on readme  
File "main.py", line 43
    except Exception, e:
